####################################################################
# This dockerfile generates Zabbix Linux packages for amd64 or s390x
# Build arguments:
#   VERSION: Zabbix version
#   GITHUB_TOKEN: GitHub token used for asset deployment
#   GITHUB_REPOSITORY: GitHub repository used
#   GITHUB_SERVER_URL: GitHub server url
#   ARCH: Value of $(uname -m)
####################################################################
FROM ubuntu:20.04 AS ubuntu-20.04-build

ARG TARGETARCH

RUN apt update -y && DEBIAN_FRONTEND=noninteractive apt install -y build-essential equivs wget
RUN wget -P /tmp https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_7.0-2%2Bubuntu20.04_all.deb && dpkg -i /tmp/zabbix-release_7.0-2+ubuntu20.04_all.deb
RUN wget -P /tmp https://go.dev/dl/go1.22.4.linux-${TARGETARCH}.tar.gz && tar -C /usr/local -xzf /tmp/go1.22.4.linux-${TARGETARCH}.tar.gz
ENV PATH=PATH=$PATH:/usr/local/go/bin

RUN apt update -y
RUN mkdir /tmp/zabbix
RUN cd /tmp/zabbix && apt source zabbix && apt build-dep -y zabbix && cd zabbix-* && dpkg-buildpackage -uc -us
RUN cd /tmp/zabbix && apt source zabbix-agent2-plugin-postgresql && cd zabbix-agent2-plugin-postgresql-* && dpkg-buildpackage -uc -us
RUN cd /tmp/zabbix && apt source zabbix-agent2-plugin-ember-plus && cd zabbix-agent2-plugin-ember-plus-* && dpkg-buildpackage -uc -us
RUN cd /tmp/zabbix && apt source zabbix-agent2-plugin-mongodb && cd zabbix-agent2-plugin-mongodb-* && dpkg-buildpackage -uc -us
RUN cd /tmp/zabbix && apt source zabbix-agent2-plugin-mssql && cd zabbix-agent2-plugin-mssql-* && dpkg-buildpackage -uc -us

FROM ubuntu:24.04 AS ubuntu-20.04

ARG VERSION
ARG GITHUB_TOKEN
ARG GITHUB_REPOSITORY
ARG GITHUB_SERVER_URL

RUN apt update -y && DEBIAN_FRONTEND=noninteractive apt install -y gh ca-certificates
RUN mkdir /tmp/zabbix
COPY --from=ubuntu-20.04-build /tmp/zabbix/*.deb /tmp/zabbix/
RUN gh release -R ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY} view ${VERSION} || gh release -R ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY} create ${VERSION} --notes ${VERSION}
RUN cd /tmp && gh release -R ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY} upload --clobber ${VERSION} /tmp/zabbix/*.deb

FROM ubuntu:22.04 AS ubuntu-22.04-build

ARG TARGETARCH

RUN apt update -y && DEBIAN_FRONTEND=noninteractive apt install -y build-essential equivs wget
RUN wget -P /tmp https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_7.0-2%2Bubuntu22.04_all.deb && dpkg -i /tmp/zabbix-release_7.0-2+ubuntu22.04_all.deb
RUN wget -P /tmp https://go.dev/dl/go1.22.4.linux-${TARGETARCH}.tar.gz && tar -C /usr/local -xzf /tmp/go1.22.4.linux-${TARGETARCH}.tar.gz
ENV PATH=PATH=$PATH:/usr/local/go/bin

RUN apt update -y
RUN mkdir /tmp/zabbix
RUN cd /tmp/zabbix && apt source zabbix && apt build-dep -y zabbix && cd zabbix-* && dpkg-buildpackage -uc -us
RUN cd /tmp/zabbix && apt source zabbix-agent2-plugin-postgresql && cd zabbix-agent2-plugin-postgresql-* && dpkg-buildpackage -uc -us
RUN cd /tmp/zabbix && apt source zabbix-agent2-plugin-ember-plus && cd zabbix-agent2-plugin-ember-plus-* && dpkg-buildpackage -uc -us
RUN cd /tmp/zabbix && apt source zabbix-agent2-plugin-mongodb && cd zabbix-agent2-plugin-mongodb-* && dpkg-buildpackage -uc -us
RUN cd /tmp/zabbix && apt source zabbix-agent2-plugin-mssql && cd zabbix-agent2-plugin-mssql-* && dpkg-buildpackage -uc -us

FROM ubuntu:24.04 AS ubuntu-22.04

ARG VERSION
ARG GITHUB_TOKEN
ARG GITHUB_REPOSITORY
ARG GITHUB_SERVER_URL

RUN apt update -y && DEBIAN_FRONTEND=noninteractive apt install -y gh ca-certificates
RUN mkdir /tmp/zabbix
COPY --from=ubuntu-22.04-build /tmp/zabbix/*.deb /tmp/zabbix/
RUN gh release -R ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY} view ${VERSION} || gh release -R ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY} create ${VERSION} --notes ${VERSION}
RUN cd /tmp && gh release -R ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY} upload --clobber ${VERSION} /tmp/zabbix/*.deb

FROM ubuntu:24.04 AS ubuntu-24.04-build

ARG TARGETARCH

RUN apt update -y && DEBIAN_FRONTEND=noninteractive apt install -y build-essential equivs wget
RUN wget -P /tmp https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_7.0-2%2Bubuntu24.04_all.deb && dpkg -i /tmp/zabbix-release_7.0-2+ubuntu24.04_all.deb
RUN wget -P /tmp https://go.dev/dl/go1.22.4.linux-${TARGETARCH}.tar.gz && tar -C /usr/local -xzf /tmp/go1.22.4.linux-${TARGETARCH}.tar.gz
ENV PATH=PATH=$PATH:/usr/local/go/bin

RUN apt update -y
RUN mkdir /tmp/zabbix
RUN cd /tmp/zabbix && apt source zabbix && apt build-dep -y zabbix && cd zabbix-* && dpkg-buildpackage -uc -us
RUN cd /tmp/zabbix && apt source zabbix-agent2-plugin-postgresql && cd zabbix-agent2-plugin-postgresql-* && dpkg-buildpackage -uc -us
RUN cd /tmp/zabbix && apt source zabbix-agent2-plugin-ember-plus && cd zabbix-agent2-plugin-ember-plus-* && dpkg-buildpackage -uc -us
RUN cd /tmp/zabbix && apt source zabbix-agent2-plugin-mongodb && cd zabbix-agent2-plugin-mongodb-* && dpkg-buildpackage -uc -us
RUN cd /tmp/zabbix && apt source zabbix-agent2-plugin-mssql && cd zabbix-agent2-plugin-mssql-* && dpkg-buildpackage -uc -us

FROM ubuntu:24.04 AS ubuntu-24.04

ARG VERSION
ARG GITHUB_TOKEN
ARG GITHUB_REPOSITORY
ARG GITHUB_SERVER_URL

RUN apt update -y && DEBIAN_FRONTEND=noninteractive apt install -y gh ca-certificates
RUN mkdir /tmp/zabbix
COPY --from=ubuntu-24.04-build /tmp/zabbix/*.deb /tmp/zabbix/
RUN gh release -R ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY} view ${VERSION} || gh release -R ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY} create ${VERSION} --notes ${VERSION}
RUN cd /tmp && gh release -R ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY} upload --clobber ${VERSION} /tmp/zabbix/*.deb

FROM rockylinux:9 AS rhel-9-build

ARG VERSION
ARG TARGETARCH

RUN dnf -y install rpm-build dnf-plugins-core gcc
RUN dnf config-manager --set-enabled crb
RUN wget -P /tmp https://go.dev/dl/go1.22.4.linux-${TARGETARCH}.tar.gz && tar -C /usr/local -xzf /tmp/go1.22.4.linux-${TARGETARCH}.tar.gz
ENV PATH=PATH=$PATH:/usr/local/go/bin
RUN dnf -y builddep https://repo.zabbix.com/zabbix/7.0/rhel/9/SRPMS/zabbix-${VERSION}-release1.el9.src.rpm
RUN rpmbuild --rebuild --define='build_agent2 1' https://repo.zabbix.com/zabbix/7.0/rhel/9/SRPMS/zabbix-${VERSION}-release1.el9.src.rpm
RUN rpmbuild --rebuild https://repo.zabbix.com/zabbix/7.0/rhel/9/SRPMS/zabbix-agent2-plugin-ember-plus-${VERSION}-release1.el9.src.rpm
RUN rpmbuild --rebuild https://repo.zabbix.com/zabbix/7.0/rhel/9/SRPMS/zabbix-agent2-plugin-mongodb-${VERSION}-release1.el9.src.rpm
RUN rpmbuild --rebuild https://repo.zabbix.com/zabbix/7.0/rhel/9/SRPMS/zabbix-agent2-plugin-mssql-${VERSION}-release1.el9.src.rpm
RUN rpmbuild --rebuild https://repo.zabbix.com/zabbix/7.0/rhel/9/SRPMS/zabbix-agent2-plugin-postgresql-${VERSION}-release1.el9.src.rpm

FROM ubuntu:24.04 AS rhel-9

ARG VERSION
ARG GITHUB_TOKEN
ARG GITHUB_REPOSITORY
ARG GITHUB_SERVER_URL
ARG ARCH

RUN apt update -y && DEBIAN_FRONTEND=noninteractive apt install -y gh ca-certificates
RUN mkdir /tmp/zabbix
COPY --from=rhel-9-build /root/rpmbuild/RPMS/${ARCH}/*.rpm /tmp/zabbix/
COPY --from=rhel-9-build /root/rpmbuild/RPMS/noarch/*.rpm /tmp/zabbix/
RUN gh release -R ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY} view ${VERSION} || gh release -R ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY} create ${VERSION} --notes ${VERSION}
RUN gh release -R ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY} upload --clobber ${VERSION} /tmp/zabbix/*.rpm

FROM ubuntu:24.04 AS all

ARG VERSION
ARG GITHUB_TOKEN
ARG GITHUB_REPOSITORY
ARG GITHUB_SERVER_URL
ARG ARCH

RUN apt update -y && DEBIAN_FRONTEND=noninteractive apt install -y gh ca-certificates
RUN mkdir /tmp/zabbix
COPY --from=ubuntu-20.04-build /tmp/zabbix/*.deb /tmp/zabbix/
COPY --from=ubuntu-22.04-build /tmp/zabbix/*.deb /tmp/zabbix/
COPY --from=ubuntu-24.04-build /tmp/zabbix/*.deb /tmp/zabbix/
COPY --from=rhel-9-build /root/rpmbuild/RPMS/${ARCH}/*.rpm /tmp/zabbix/
COPY --from=rhel-9-build /root/rpmbuild/RPMS/noarch/*.rpm /tmp/zabbix/
RUN gh release -R ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY} view ${VERSION} || gh release -R ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY} create ${VERSION} --notes ${VERSION}
RUN cd /tmp && gh release -R ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY} upload --clobber ${VERSION} /tmp/zabbix/*
