on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Select Zabbix Version'
        required: true
        default: '7.0.0'
        type: choice
        options:
          - '7.0.0'
      target:
        description: 'Select Target Distro'
        required: true
        default: all
        type: choice
        options:
          - all
          - ubuntu-18.04
          - ubuntu-20.04
          - ubuntu-22.04
          - ubuntu-24.04
          - rhel-9

# Make sure the GITHUB_TOKEN has permission to upload to our releases
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build 
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile_${{ inputs.version }}
          push: false
          platforms: linux/s390x
          build-args: |
            GITHUB_TOKEN=${{ github.token }}
            GITHUB_SERVER_URL=${{ github.server_url }}
            GITHUB_REPOSITORY=${{ github.repository }}
            VERSION=${{ inputs.version }}
          outputs: type=tar,dest=/dev/null
          target: ${{ inputs.target }}
